{{- if .Values.nfd.nodefeaturerules }}
apiVersion: nfd.k8s-sigs.io/v1alpha1
kind: NodeFeatureRule
metadata:
  name: nvidia-nfd-nodefeaturerules
spec:
  rules:
    - name: "TDX rule"
      labels:
        tdx.enabled: "true"
      matchFeatures:
        - feature: cpu.security
          matchExpressions:
              tdx.enabled: {op: IsTrue}
    - name: "TDX total keys rule"
      extendedResources:
        tdx.total_keys: "@cpu.security.tdx.total_keys"
      matchFeatures:
        - feature: cpu.security
          matchExpressions:
            tdx.enabled: {op: IsTrue}
    - name: "SEV-SNP rule"
      labels:
        sev.snp.enabled: "true"
      matchFeatures:
      - feature: cpu.security
        matchExpressions:
          sev.snp.enabled:
            op: IsTrue
    - name: "SEV-ES rule"
      labels:
        sev.es.enabled: "true"
      matchFeatures:
      - feature: cpu.security
        matchExpressions:
          sev.es.enabled:
            op: IsTrue
    - name: SEV system capacities
      extendedResources:
        sev_asids: '@cpu.security.sev.asids'
        sev_es: '@cpu.security.sev.encrypted_state_ids'
      matchFeatures:
      - feature: cpu.security
        matchExpressions:
          sev.enabled:
            op: Exists
    - name: "NVIDIA Hopper GPU"
      labels:
        "nvidia.com/gpu.family": "hopper"
      matchFeatures:
        - feature: pci.device
          matchExpressions:
            vendor: {op: In, value: ["10de"]}
            # H100/H800 (0x2300-0x23ff) from https://admin.pci-ids.ucw.cz/read/PC/10de
            device: {op: InRegexp, value: ["^23[0-9a-f]{2}$"]}
    - name: "NVIDIA Blackwell GPU"
      labels:
        "nvidia.com/gpu.family": "blackwell"
      matchFeatures:
        - feature: pci.device
          matchExpressions:
            vendor: {op: In, value: ["10de"]}
            # GB202-GB207, GB110-GB120 (0x2b00-0x33ff) from https://admin.pci-ids.ucw.cz/read/PC/10de
            device: {op: InRegexp, value: ["^(2[b-f]|3[0-3])[0-9a-f]{2}$"]}
    - name: "NVIDIA CC Enabled"
      labels:
        "nvidia.com/cc.capable": "true"
      matchAny: # TDX/SEV + Hopper/Blackwell GPU
       - matchFeatures:
          - feature: rule.matched
            matchExpressions:
              nvidia.com/gpu.family: {op: In, value: ["hopper", "blackwell"]}
              sev.snp.enabled: {op: IsTrue}
       - matchFeatures:
          - feature: rule.matched
            matchExpressions:
              nvidia.com/gpu.family: {op: In, value: ["hopper", "blackwell"]}
              tdx.enabled: {op: IsTrue}
{{- end }}

